name: flutter_template
description: A new Flutter template.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 屏幕适配
  flutter_screenutil: ^2.3.1
  # toast
  fluttertoast: ^3.1.3
  # http
  dio: ^3.0.10
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  # storage + cached  后续考虑加入sq 本地数据库
  shared_preferences: ^0.5.10
  cached_network_image: ^2.0.0
  # 状态管理 采用的是provider 暂时没有打算使用 bloc
  provider: ^4.3.2+1
  # 加密
  crypto: ^2.1.3
  # 日期格式
  intl: ^0.16.1
  # UI 下拉刷新组件
  flutter_easyrefresh: ^2.1.0
  # 骨架屏
  pk_skeleton: ^0.0.2
  # 路由管理 https://github.com/Milad-Akarie/auto_route_library
  auto_route: ^0.5.0
  # WebView 反义 淘宝 等app 会发现详情页 动态页都是采用混合的方式
  webview_flutter: ^0.3.22+1
  # loading
  loading_animations: ^2.1.0
  # share
  share: ^0.6.4
  # ios风格
  cupertino_icons: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  # 路由生成
  auto_route_generator: ^0.5.0
  build_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf